name: re_walls
description: Wallpapers from reddit.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  carousel_slider: ^1.3.0
  shared_preferences: ^0.5.7
  http:
  cached_network_image: ^2.1.0+1
  share: ^0.6.3+1
  webview_flutter: ^0.3.15+1
  image_downloader: ^0.19.1
  font_awesome_flutter: ^8.5.0
  shimmer: ^1.0.1
  flutter_cache_manager: ^1.1.3
  permission_handler: ^4.0.0
  fluttertoast: ^3.1.3
  url_launcher: "5.2.7"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
